use super::{RootCaPem, certificate_fingerprint_sha256, generate_root_ca};
use crate::{PlatformError, PlatformResult};
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Clone, Debug, PartialEq, Eq)]
/// Deterministic filesystem layout for one rsproxy certificate authority.
pub struct CaPaths {
    /// Root directory containing all CA-owned files.
    pub directory: PathBuf,
    /// PEM root certificate path.
    pub certificate: PathBuf,
    /// PEM root private-key path, written with owner-only permissions on Unix.
    pub private_key: PathBuf,
    /// Safety notice written alongside generated root material.
    pub readme: PathBuf,
    /// Directory containing cached per-host leaf certificate material.
    pub leaf_directory: PathBuf,
}

impl CaPaths {
    /// Derives the stable rsproxy filenames beneath `directory` without touching the filesystem.
    pub fn new(directory: impl Into<PathBuf>) -> Self {
        let directory = directory.into();
        Self {
            certificate: directory.join("rsproxy-root-ca.pem"),
            private_key: directory.join("rsproxy-root-ca-key.pem"),
            readme: directory.join("README.txt"),
            leaf_directory: directory.join("leaf"),
            directory,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
/// Result of ensuring root CA material exists on disk.
pub enum CaInitialization {
    /// Both root files already existed and `force` was not requested.
    AlreadyInitialized {
        /// Existing CA filesystem layout.
        paths: CaPaths,
    },
    /// New root certificate and private key were generated and persisted.
    Created {
        /// Newly written CA filesystem layout.
        paths: CaPaths,
        /// Uppercase, colon-delimited SHA-256 certificate fingerprint.
        fingerprint_sha256: String,
    },
}

#[derive(Clone, Debug, PartialEq, Eq)]
/// Filesystem health and cache summary for persistent root CA material.
pub struct CaStatus {
    /// Expected CA filesystem layout.
    pub paths: CaPaths,
    /// Whether both the root certificate and private key are regular files.
    pub initialized: bool,
    /// Whether the root certificate is a regular file.
    pub certificate_exists: bool,
    /// Whether the root private key is a regular file.
    pub private_key_exists: bool,
    /// Number of cached leaf certificate files, excluding key and chain files.
    pub leaf_cached: usize,
    /// Root SHA-256 fingerprint, `invalid-pem`, or `-` when no certificate exists.
    pub fingerprint_sha256: String,
}

#[derive(Clone, Debug, PartialEq, Eq)]
/// Deterministic paths for one cached host certificate bundle.
pub struct LeafPaths {
    /// PEM leaf certificate path.
    pub certificate: PathBuf,
    /// PEM leaf private-key path, written with owner-only permissions on Unix.
    pub private_key: PathBuf,
    /// PEM certificate-chain path presented with the leaf.
    pub chain: PathBuf,
}

#[derive(Clone, Debug, PartialEq, Eq)]
/// Metadata returned after locating or writing a complete cached leaf bundle.
pub struct StoredLeafCertificate {
    /// Paths to the certificate, private key, and chain files.
    pub paths: LeafPaths,
    /// Uppercase, colon-delimited SHA-256 leaf certificate fingerprint.
    pub fingerprint_sha256: String,
}

/// Creates persistent root material, or reports an existing complete installation.
///
/// Partial state is rejected unless `force` is true. With `force`, existing root files are
/// replaced but the leaf cache is not cleared. On Unix the private key is set to mode `0600`.
pub fn initialize_root_ca(
    ca_directory: &Path,
    common_name: &str,
    force: bool,
) -> PlatformResult<CaInitialization> {
    let paths = CaPaths::new(ca_directory);
    let certificate_exists = paths.certificate.exists();
    let private_key_exists = paths.private_key.exists();
    if certificate_exists && private_key_exists && !force {
        return Ok(CaInitialization::AlreadyInitialized { paths });
    }
    if (certificate_exists || private_key_exists) && !force {
        return Err(PlatformError::InvalidState(format!(
            "partial CA state in {}; rerun `rsproxy ca init --force` to replace it",
            ca_directory.display()
        )));
    }

    fs::create_dir_all(ca_directory).map_err(|source| PlatformError::Io {
        context: format!("create CA directory {}", ca_directory.display()),
        source,
    })?;
    let root = generate_root_ca(common_name)?;
    fs::write(&paths.certificate, root.certificate_pem.as_bytes()).map_err(|source| {
        PlatformError::Io {
            context: format!("write {}", paths.certificate.display()),
            source,
        }
    })?;
    write_private_key(&paths.private_key, root.private_key_pem.as_bytes())?;
    fs::write(
        &paths.readme,
        "Generated by rsproxy. Trust rsproxy-root-ca.pem only on devices you control, and keep rsproxy-root-ca-key.pem private.\n",
    )
    .map_err(|source| PlatformError::Io {
        context: format!("write {}", paths.readme.display()),
        source,
    })?;
    let fingerprint_sha256 = certificate_fingerprint_sha256(&root.certificate_pem)
        .unwrap_or_else(|| "unknown".to_string());
    Ok(CaInitialization::Created {
        paths,
        fingerprint_sha256,
    })
}

/// Inspects expected root files and counts cached leaf certificates without changing disk state.
pub fn root_ca_status(ca_directory: &Path) -> PlatformResult<CaStatus> {
    let paths = CaPaths::new(ca_directory);
    let certificate_exists = paths.certificate.is_file();
    let private_key_exists = paths.private_key.is_file();
    let fingerprint_sha256 = if certificate_exists {
        let certificate =
            fs::read_to_string(&paths.certificate).map_err(|source| PlatformError::Io {
                context: format!("read {}", paths.certificate.display()),
                source,
            })?;
        certificate_fingerprint_sha256(&certificate).unwrap_or_else(|| "invalid-pem".to_string())
    } else {
        "-".to_string()
    };
    Ok(CaStatus {
        initialized: certificate_exists && private_key_exists,
        certificate_exists,
        private_key_exists,
        leaf_cached: leaf_cache_count(&paths.leaf_directory),
        fingerprint_sha256,
        paths,
    })
}

/// Reads both PEM root files from the deterministic CA layout.
pub fn read_root_ca(ca_directory: &Path) -> PlatformResult<RootCaPem> {
    let paths = CaPaths::new(ca_directory);
    Ok(RootCaPem {
        certificate_pem: fs::read_to_string(&paths.certificate).map_err(|source| {
            PlatformError::Io {
                context: format!("read {}", paths.certificate.display()),
                source,
            }
        })?,
        private_key_pem: fs::read_to_string(&paths.private_key).map_err(|source| {
            PlatformError::Io {
                context: format!("read {}", paths.private_key.display()),
                source,
            }
        })?,
    })
}

/// Reads only the PEM root certificate, leaving the private key untouched.
pub fn read_root_certificate(ca_directory: &Path) -> PlatformResult<String> {
    let path = CaPaths::new(ca_directory).certificate;
    fs::read_to_string(&path).map_err(|source| PlatformError::Io {
        context: format!("read {}", path.display()),
        source,
    })
}

/// Derives safe cache paths for `host` without reading or writing the filesystem.
pub fn leaf_paths(ca_directory: &Path, host: &str) -> LeafPaths {
    let directory = CaPaths::new(ca_directory).leaf_directory;
    let cache_name = leaf_cache_name(host);
    LeafPaths {
        certificate: directory.join(format!("{cache_name}.pem")),
        private_key: directory.join(format!("{cache_name}-key.pem")),
        chain: directory.join(format!("{cache_name}-chain.pem")),
    }
}

/// Returns a cached leaf only when its certificate, key, and chain files all exist.
///
/// Incomplete bundles are treated as cache misses rather than errors.
pub fn cached_leaf_certificate(
    ca_directory: &Path,
    host: &str,
) -> PlatformResult<Option<StoredLeafCertificate>> {
    let paths = leaf_paths(ca_directory, host);
    if !(paths.certificate.is_file() && paths.private_key.is_file() && paths.chain.is_file()) {
        return Ok(None);
    }
    let certificate =
        fs::read_to_string(&paths.certificate).map_err(|source| PlatformError::Io {
            context: format!("read {}", paths.certificate.display()),
            source,
        })?;
    Ok(Some(StoredLeafCertificate {
        fingerprint_sha256: certificate_fingerprint_sha256(&certificate)
            .unwrap_or_else(|| "unknown".to_string()),
        paths,
    }))
}

/// Writes a complete leaf certificate bundle and returns its paths and fingerprint.
///
/// The cache directory is created when necessary. On Unix the private key is set to mode `0600`.
pub fn store_leaf_certificate(
    ca_directory: &Path,
    host: &str,
    certificate_pem: &str,
    private_key_pem: &str,
    chain_pem: &str,
) -> PlatformResult<StoredLeafCertificate> {
    let paths = leaf_paths(ca_directory, host);
    let directory = paths
        .certificate
        .parent()
        .expect("leaf certificate path always has a parent");
    fs::create_dir_all(directory).map_err(|source| PlatformError::Io {
        context: format!("create leaf certificate directory {}", directory.display()),
        source,
    })?;
    fs::write(&paths.certificate, certificate_pem.as_bytes()).map_err(|source| {
        PlatformError::Io {
            context: format!("write {}", paths.certificate.display()),
            source,
        }
    })?;
    write_private_key(&paths.private_key, private_key_pem.as_bytes())?;
    fs::write(&paths.chain, chain_pem.as_bytes()).map_err(|source| PlatformError::Io {
        context: format!("write {}", paths.chain.display()),
        source,
    })?;
    Ok(StoredLeafCertificate {
        fingerprint_sha256: certificate_fingerprint_sha256(certificate_pem)
            .unwrap_or_else(|| "unknown".to_string()),
        paths,
    })
}

/// Maps a host to a lowercase, path-safe cache component.
///
/// ASCII alphanumerics, `.`, `-`, and `_` are preserved; every other character becomes `_`.
pub fn leaf_cache_name(host: &str) -> String {
    host.chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() || matches!(character, '.' | '-' | '_') {
                character.to_ascii_lowercase()
            } else {
                '_'
            }
        })
        .collect()
}

fn leaf_cache_count(leaf_directory: &Path) -> usize {
    let Ok(entries) = fs::read_dir(leaf_directory) else {
        return 0;
    };
    entries
        .flatten()
        .filter(|entry| {
            entry.file_type().map(|ty| ty.is_file()).unwrap_or(false)
                && entry.file_name().to_str().is_some_and(|name| {
                    name.ends_with(".pem")
                        && !name.ends_with("-key.pem")
                        && !name.ends_with("-chain.pem")
                })
        })
        .count()
}

fn write_private_key(path: &Path, body: &[u8]) -> PlatformResult<()> {
    fs::write(path, body).map_err(|source| PlatformError::Io {
        context: format!("write {}", path.display()),
        source,
    })?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(path, fs::Permissions::from_mode(0o600)).map_err(|source| {
            PlatformError::Io {
                context: format!("set private permissions on {}", path.display()),
                source,
            }
        })?;
    }
    Ok(())
}
