pub(super) struct WorkflowContract {
    pub file: &'static str,
    pub required: &'static [&'static str],
    pub rejected: &'static [&'static str],
}

pub(super) const CONTRACTS: &[WorkflowContract] = &[
    WorkflowContract {
        file: "ci.yml",
        required: &[
            "name: CI",
            "push:",
            "branches: [main]",
            "pull_request:",
            "merge_group:",
            "workflow_dispatch:",
            "contents: read",
            "concurrency:",
            "group: ci-${{ github.ref }}",
            "cancel-in-progress: ${{ github.event_name == 'pull_request' }}",
            // Manual approval gate: PR runs wait for the ci-approval
            // environment; non-PR events skip the gate and run directly.
            "environment: ci-approval",
            "if: github.event_name == 'pull_request'",
            "needs: gate",
            "if: ${{ !cancelled() && (needs.gate.result == 'success' || needs.gate.result == 'skipped') }}",
            "fail-fast: false",
            "ubuntu-latest",
            "macos-latest",
            "windows-latest",
            "actions/checkout@v6",
            "actions/setup-node@v6",
            "oven-sh/setup-bun@v2",
            "bun-version: 1.3.11",
            "dtolnay/rust-toolchain@stable",
            "dtolnay/rust-toolchain@1.88.0",
            "Swatinem/rust-cache@v2",
            "components: rustfmt, clippy",
            "rustup toolchain install nightly-2026-07-10 --profile minimal",
            "cargo install cargo-public-api --version 0.52.0 --locked",
            "cargo fmt --all -- --check",
            "cargo clippy --workspace --all-targets --locked -- -D warnings",
            "RUSTDOCFLAGS=\"-D warnings\" cargo doc --workspace --no-deps --locked",
            "cargo check --workspace --all-targets --locked",
            "cargo check --workspace --locked",
            "cargo install cargo-nextest --version 0.9.140 --locked",
            "cargo nextest run --workspace --all-targets --no-fail-fast --locked",
            "cargo build --release --workspace --locked",
            "cargo xtask check all",
            "cargo xtask check lines",
            "cargo xtask check layout",
            "cargo xtask check typed-errors",
            "cargo xtask check workflows",
            "EmbarkStudios/cargo-deny-action@v2",
            "rust-version: \"1.88\"",
            "command: check",
            "arguments: --all-features --locked",
            "command-arguments: advisories bans licenses sources",
            "find scripts benches -type f -name '*.sh' -exec sh -n {} \\;",
            "cargo check --manifest-path fuzz/Cargo.toml --bin parse_resolve --locked",
            "./scripts/verify.sh matrix",
            "./scripts/verify.sh actions",
            "./scripts/verify.sh package",
            "components: llvm-tools-preview",
            "cargo install cargo-llvm-cov --version 0.6.21 --locked",
            "./scripts/verify.sh coverage-report",
            "name: coverage-report",
            "target/coverage",
            "if-no-files-found: error",
        ],
        rejected: &[],
    },
    WorkflowContract {
        file: "fuzz.yml",
        required: &[
            "name: Rules fuzz",
            "schedule:",
            "cron: \"17 3 * * *\"",
            "workflow_dispatch:",
            "contents: read",
            "group: rules-fuzz",
            "cancel-in-progress: false",
            "RSPROXY_FUZZ_RUNS: \"0\"",
            "RSPROXY_FUZZ_SECONDS: \"300\"",
            "RSPROXY_FUZZ_MAX_LEN: \"65536\"",
            "actions/checkout@v6",
            "dtolnay/rust-toolchain@nightly",
            "Swatinem/rust-cache@v2",
            "cargo install cargo-fuzz --version 0.13.2 --locked",
            "cargo test -p rsproxy-rules --test it fuzz_seeds:: --locked",
            "./scripts/verify.sh fuzz",
            "if: failure()",
            "actions/upload-artifact@v6",
            "path: fuzz/artifacts/parse_resolve",
            "if-no-files-found: ignore",
            "retention-days: 14",
        ],
        rejected: &[],
    },
    WorkflowContract {
        file: "performance.yml",
        required: &[
            "name: Performance",
            "schedule:",
            "cron: \"41 2 * * *\"",
            "workflow_dispatch:",
            "contents: read",
            "group: criterion-${{ github.ref }}",
            "cancel-in-progress: true",
            "fetch-depth: 0",
            "benches/criterion/run.sh",
            "cargo xtask targets criterion target/performance/criterion.json",
            "cargo xtask targets regression \"$RUNNER_TEMP/criterion-base.json\" target/performance/criterion.json 10",
            "target/performance/criterion.json",
            "actions/upload-artifact@v6",
            "if-no-files-found: error",
            "persist-credentials: false",
        ],
        rejected: &[],
    },
    WorkflowContract {
        file: "release.yml",
        required: &[
            "name: Release",
            "tags:",
            "workflow_dispatch:",
            "contents: read",
            "concurrency:",
            "group: release-${{ github.ref }}",
            "cancel-in-progress: false",
            "fail-fast: false",
            "ubuntu-24.04-arm",
            "macos-15-intel",
            "windows-11-arm",
            "x86_64-unknown-linux-gnu",
            "x86_64-unknown-linux-musl",
            "aarch64-unknown-linux-gnu",
            "aarch64-unknown-linux-musl",
            "aarch64-apple-darwin",
            "x86_64-apple-darwin",
            "aarch64-pc-windows-msvc",
            "x86_64-pc-windows-msvc",
            "musl-tools",
            "cargo xtask release \"$version\" --check",
            "cargo build --release -p rsproxy-cli --bin rsproxy --target ${{ matrix.target }} --locked",
            "./scripts/package-npm.sh native",
            "./scripts/package-npm.sh launchers",
            "actions/upload-artifact@v6",
            "actions/download-artifact@v6",
            "if-no-files-found: error",
            "id-token: write",
            "registry-url: https://registry.npmjs.org",
            "NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}",
            "npm publish",
            "--access public --provenance",
            "rsproxy-runtime",
            "rsproxy-cli",
            "rsproxy-bun",
            "persist-credentials: false",
            // Job-scoped release permissions and GitHub release assets.
            "      contents: write",
            "dist/github",
            "rsproxy-v${version}-${{ matrix.target }}",
            "tar -czf",
            "shasum -a 256",
            "SHA256SUMS",
            "GH_TOKEN: ${{ github.token }}",
            "gh release create \"$GITHUB_REF_NAME\" --verify-tag",
            "--notes-file",
            "CHANGELOG.md",
        ],
        // Workflow-level write permissions are rejected structurally for every
        // workflow (see `workflow_permission_violations`); the six-space
        // required string above pins the write grant to the job level.
        rejected: &[],
    },
];

pub(super) const GLOBAL_REJECTED: &[&str] = &[
    "continue-on-error:",
    "@main",
    "@master",
    "@latest",
    "check.sh",
    "targets.sh",
];
