pub(super) struct WorkflowContract {
    pub file: &'static str,
    pub required: &'static [&'static str],
    pub rejected: &'static [&'static str],
}

pub(super) const CONTRACTS: &[WorkflowContract] = &[
    WorkflowContract {
        file: "ci.yml",
        required: &[
            "name: CI",
            "push:",
            "pull_request:",
            "workflow_dispatch:",
            "contents: read",
            "fail-fast: false",
            "ubuntu-latest",
            "macos-latest",
            "windows-latest",
            "actions/checkout@v6",
            "actions/setup-node@v6",
            "oven-sh/setup-bun@v2",
            "bun-version: 1.3.11",
            "dtolnay/rust-toolchain@stable",
            "dtolnay/rust-toolchain@1.88.0",
            "Swatinem/rust-cache@v2",
            "components: rustfmt, clippy",
            "cargo fmt --all -- --check",
            "cargo clippy --workspace --all-targets --locked -- -D warnings",
            "cargo check --workspace --all-targets --locked",
            "cargo check --workspace --locked",
            "cargo test --workspace --all-targets --no-fail-fast --locked",
            "cargo build --release --workspace --locked",
            "cargo xtask check all",
            "EmbarkStudios/cargo-deny-action@v2",
            "rust-version: \"1.88\"",
            "command: check",
            "arguments: --all-features --locked",
            "command-arguments: advisories bans licenses sources",
            "find scripts benches -type f -name '*.sh' -exec sh -n {} \\;",
            "cargo check --manifest-path fuzz/Cargo.toml --bin parse_resolve --locked",
            "./scripts/verify.sh matrix",
            "./scripts/verify.sh actions",
            "./scripts/verify.sh package",
            "components: llvm-tools-preview",
            "cargo install cargo-llvm-cov --version 0.6.21 --locked",
            "./scripts/verify.sh coverage-report",
            "name: coverage-report",
            "target/coverage",
            "if-no-files-found: error",
        ],
        rejected: &[],
    },
    WorkflowContract {
        file: "fuzz.yml",
        required: &[
            "name: Rules fuzz",
            "schedule:",
            "cron: \"17 3 * * *\"",
            "workflow_dispatch:",
            "contents: read",
            "group: rules-fuzz",
            "cancel-in-progress: false",
            "RSPROXY_FUZZ_RUNS: \"0\"",
            "RSPROXY_FUZZ_SECONDS: \"300\"",
            "RSPROXY_FUZZ_MAX_LEN: \"65536\"",
            "actions/checkout@v6",
            "dtolnay/rust-toolchain@nightly",
            "Swatinem/rust-cache@v2",
            "cargo install cargo-fuzz --version 0.13.2 --locked",
            "cargo test -p rsproxy-rules --test fuzz_seeds --locked",
            "./scripts/verify.sh fuzz",
            "if: failure()",
            "actions/upload-artifact@v6",
            "path: fuzz/artifacts/parse_resolve",
            "if-no-files-found: ignore",
            "retention-days: 14",
        ],
        rejected: &[],
    },
    WorkflowContract {
        file: "performance.yml",
        required: &[
            "name: Performance",
            "pull_request:",
            "schedule:",
            "cron: \"41 2 * * *\"",
            "workflow_dispatch:",
            "contents: read",
            "group: criterion-${{ github.ref }}",
            "cancel-in-progress: true",
            "fetch-depth: 0",
            "benches/criterion/run.sh",
            "cargo xtask targets criterion target/performance/criterion.json",
            "cargo xtask targets regression \"$RUNNER_TEMP/criterion-base.json\" target/performance/criterion.json 10",
            "target/performance/criterion.json",
            "actions/upload-artifact@v6",
            "if-no-files-found: error",
            "persist-credentials: false",
        ],
        rejected: &[],
    },
    WorkflowContract {
        file: "release.yml",
        required: &[
            "name: Release",
            "tags:",
            "workflow_dispatch:",
            "contents: read",
            "fail-fast: false",
            "ubuntu-24.04-arm",
            "macos-15-intel",
            "windows-11-arm",
            "x86_64-unknown-linux-gnu",
            "x86_64-unknown-linux-musl",
            "aarch64-unknown-linux-gnu",
            "aarch64-unknown-linux-musl",
            "aarch64-apple-darwin",
            "x86_64-apple-darwin",
            "aarch64-pc-windows-msvc",
            "x86_64-pc-windows-msvc",
            "musl-tools",
            "cargo xtask release \"$version\" --check",
            "cargo build --release -p rsproxy-cli --bin rsproxy --target ${{ matrix.target }} --locked",
            "./scripts/package-npm.sh native",
            "./scripts/package-npm.sh launchers",
            "actions/upload-artifact@v6",
            "actions/download-artifact@v6",
            "if-no-files-found: error",
            "id-token: write",
            "registry-url: https://registry.npmjs.org",
            "NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}",
            "npm publish",
            "--access public --provenance",
            "rsproxy-runtime",
            "rsproxy-cli",
            "rsproxy-bun",
            "persist-credentials: false",
        ],
        rejected: &["gh release", "*.tar.gz", "contents: write"],
    },
];

pub(super) const GLOBAL_REJECTED: &[&str] = &[
    "continue-on-error:",
    "@main",
    "@master",
    "@latest",
    "check.sh",
    "targets.sh",
];
