use super::*;

pub(crate) mod certificates;
mod storage;
mod trust;

pub(super) use certificates::*;
pub(super) use storage::*;
pub(super) use trust::*;

pub(super) fn ca_cmd(args: Vec<String>) -> Result<(), String> {
    let storage = runtime_config(&args)?.storage;
    let ca_dir = storage.join("ca");
    let sub = args.first().map(String::as_str).unwrap_or("status");
    match sub {
        "init" => ca_init(&args, &ca_dir),
        "status" => ca_status(&args, &ca_dir),
        "export" => ca_export(&args, &ca_dir),
        "issue" => ca_issue(&args, &ca_dir),
        "install" => ca_install(&args, &ca_dir),
        "uninstall" => ca_uninstall(&args, &ca_dir),
        _ => Err(format!("unknown ca command `{sub}`")),
    }
}

pub(super) fn ca_init(args: &[String], ca_dir: &Path) -> Result<(), String> {
    let cert_path = ca_dir.join("rsproxy-root-ca.pem");
    let key_path = ca_dir.join("rsproxy-root-ca-key.pem");
    let force = has_flag(args, "--force");
    if cert_path.exists() && key_path.exists() && !force {
        println!(
            "already initialized cert={} key={}",
            cert_path.display(),
            key_path.display()
        );
        return Ok(());
    }
    if (cert_path.exists() || key_path.exists()) && !force {
        return Err(format!(
            "partial CA state in {}; rerun `rsproxy ca init --force` to replace it",
            ca_dir.display()
        ));
    }

    fs::create_dir_all(ca_dir).map_err(|e| e.to_string())?;
    let common_name =
        option_value(args, "--name").unwrap_or_else(|| "rsproxy local root CA".to_string());
    let (cert_pem, key_pem) = generate_root_ca(&common_name)?;
    fs::write(&cert_path, cert_pem.as_bytes()).map_err(|e| e.to_string())?;
    write_private_key(&key_path, key_pem.as_bytes())?;
    fs::write(
        ca_dir.join("README.txt"),
        "Generated by rsproxy. Trust rsproxy-root-ca.pem only on devices you control, and keep rsproxy-root-ca-key.pem private.\n",
    )
    .map_err(|e| e.to_string())?;

    println!(
        "initialized cert={} key={} fingerprint_sha256={}",
        cert_path.display(),
        key_path.display(),
        cert_fingerprint(&cert_pem).unwrap_or_else(|| "unknown".to_string())
    );
    Ok(())
}

pub(super) fn ca_status(args: &[String], ca_dir: &Path) -> Result<(), String> {
    let cert_path = ca_dir.join("rsproxy-root-ca.pem");
    let key_path = ca_dir.join("rsproxy-root-ca-key.pem");
    let cert_exists = cert_path.is_file();
    let key_exists = key_path.is_file();
    let initialized = cert_exists && key_exists;
    let fingerprint = if cert_exists {
        let cert = fs::read_to_string(&cert_path).map_err(|e| e.to_string())?;
        cert_fingerprint(&cert).unwrap_or_else(|| "invalid-pem".to_string())
    } else {
        "-".to_string()
    };
    let leaf_cached = leaf_cache_count(ca_dir);
    let keychain = ca_keychain_arg(args)?;
    let installed = if let Some(keychain) = &keychain {
        let installed = if cert_exists {
            ca_keychain_contains_fingerprint(keychain, &fingerprint)?
        } else {
            false
        };
        Some(installed)
    } else {
        None
    };
    if has_flag(args, "--json") {
        println!(
            "{}",
            serde_json::json!({
                "ca_dir": ca_dir.display().to_string(),
                "initialized": initialized,
                "cert": cert_exists,
                "key": key_exists,
                "leaf_cached": leaf_cached,
                "fingerprint_sha256": fingerprint,
                "cert_path": initialized.then(|| cert_path.display().to_string()),
                "key_path": initialized.then(|| key_path.display().to_string()),
                "keychain": keychain.as_ref().map(|path| path.display().to_string()),
                "installed": installed,
            })
        );
        return Ok(());
    }
    println!(
        "ca_dir={} initialized={} cert={} key={} leaf_cached={} fingerprint_sha256={}",
        ca_dir.display(),
        initialized,
        cert_exists,
        key_exists,
        leaf_cached,
        fingerprint
    );
    if initialized {
        println!("cert_path={}", cert_path.display());
        println!("key_path={}", key_path.display());
    }
    if let Some(keychain) = keychain {
        println!(
            "keychain={} installed={}",
            keychain.display(),
            installed.unwrap_or(false)
        );
    }
    Ok(())
}

pub(super) fn ca_export(args: &[String], ca_dir: &Path) -> Result<(), String> {
    let cert_path = ca_dir.join("rsproxy-root-ca.pem");
    let cert =
        fs::read_to_string(&cert_path).map_err(|e| format!("read {}: {e}", cert_path.display()))?;
    if let Some(out) = option_value(args, "--out").or_else(|| option_value(args, "-o")) {
        fs::write(&out, cert).map_err(|e| e.to_string())?;
        println!("wrote {out}");
    } else {
        print!("{cert}");
    }
    Ok(())
}

pub(super) fn ca_issue(args: &[String], ca_dir: &Path) -> Result<(), String> {
    let host = ca_issue_host(args).ok_or_else(|| "ca issue requires host".to_string())?;
    validate_leaf_host(&host)?;
    let leaf_dir = ca_dir.join("leaf");
    let cache_name = leaf_cache_name(&host);
    let cert_path = leaf_dir.join(format!("{cache_name}.pem"));
    let key_path = leaf_dir.join(format!("{cache_name}-key.pem"));
    let chain_path = leaf_dir.join(format!("{cache_name}-chain.pem"));
    let force = has_flag(args, "--force");

    if cert_path.exists() && key_path.exists() && chain_path.exists() && !force {
        let cert = fs::read_to_string(&cert_path).map_err(|e| e.to_string())?;
        println!(
            "cached host={} cert={} key={} chain={} fingerprint_sha256={}",
            host,
            cert_path.display(),
            key_path.display(),
            chain_path.display(),
            cert_fingerprint(&cert).unwrap_or_else(|| "unknown".to_string())
        );
        return Ok(());
    }

    let (cert_pem, key_pem, chain_pem) = generate_leaf_cert(ca_dir, &host)?;
    fs::create_dir_all(&leaf_dir).map_err(|e| e.to_string())?;
    fs::write(&cert_path, cert_pem.as_bytes()).map_err(|e| e.to_string())?;
    write_private_key(&key_path, key_pem.as_bytes())?;
    fs::write(&chain_path, chain_pem.as_bytes()).map_err(|e| e.to_string())?;

    println!(
        "issued host={} cert={} key={} chain={} fingerprint_sha256={}",
        host,
        cert_path.display(),
        key_path.display(),
        chain_path.display(),
        cert_fingerprint(&cert_pem).unwrap_or_else(|| "unknown".to_string())
    );
    Ok(())
}

pub(super) fn ca_issue_host(args: &[String]) -> Option<String> {
    let mut idx = 1;
    while idx < args.len() {
        let arg = &args[idx];
        if matches!(
            arg.as_str(),
            "--config" | "--storage" | "--name" | "--out" | "-o" | "--keychain"
        ) {
            idx += 2;
            continue;
        }
        if arg.starts_with('-') {
            idx += 1;
            continue;
        }
        return Some(arg.clone());
    }
    None
}
